In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [24]:

a = np.zeros(5)
print(a)

print()

a = np.zeros((3,5))
print(a)

print()
b = np.ones(5)
print(b)

print()

b = np.ones((3,5))
print(b)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
# if i want to print another number so we have to use full()
c = np.full((3,5),7)
print(c)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [40]:
d = np.eye(3) # identity matrix 
print(d)
print()

e = np.arange(1,100,20)
print(e)
print()

f = np.linspace(0,1,5)   # it divide equally in 5 elements
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 1 21 41 61 81]

[0.   0.25 0.5  0.75 1.  ]


In [44]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]])
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [52]:
# checking array properties 

print(my_arr.shape)
print(my_arr.size)
print(my_arr.ndim)
print(my_arr.dtype)


(4, 3)
12
2
int64


In [60]:
# changing data type
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]], dtype='float64') # explicit type 
print(my_arr)
print()

n = my_arr.astype(np.int64)
print(n)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [3. 2. 1.]]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 1]]


In [68]:
print(my_arr)
print(my_arr.shape)

print()

reshaped = my_arr.reshape((2,6))   # by this we can reshape our array 
print(reshaped)

print()

print(my_arr.flatten())  # convert into 1d array 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [3. 2. 1.]]
(4, 3)

[[1. 2. 3. 4. 5. 6.]
 [7. 8. 9. 3. 2. 1.]]

[1. 2. 3. 4. 5. 6. 7. 8. 9. 3. 2. 1.]
